try {
throw 2;} catch(x) { alert (x); }
